const samples={guia:{src:'assets/guia-4.webp',alt:'Lição A Criação, página real do Guia do Professor',note:'História, perguntas, dinâmica e oração em uma sequência para conduzir a aula.'},colorir:{src:'assets/colorir-3.webp',alt:'Atividades reais para colorir: A Criação e Adão e Eva',note:'52 atividades para colorir, incluídas nas duas edições. Imprima as folhas que pretende usar.'},atividades:{src:'assets/atividades-3.webp',alt:'Atividades complementares reais das lições A Criação e Adão e Eva',note:'104 atividades complementares na Completa: propostas para observar, relacionar e conversar.'},cartoes:{src:'assets/cartoes-3.webp',alt:'Página real de cartões de versículos',note:'Bônus da Completa: 52 cartões de versículos organizados por lição, distribuídos em 10 páginas.'}};
const sampleImage=document.querySelector('#sample-image');
document.querySelectorAll('[data-sample]').forEach((tab,index,tabs)=>{tab.addEventListener('click',()=>{tabs.forEach(t=>t.setAttribute('aria-selected','false'));tab.setAttribute('aria-selected','true');const s=samples[tab.dataset.sample];sampleImage.src=s.src;sampleImage.alt=s.alt;document.querySelector('#sample-note').textContent=s.note;document.querySelector('#sample-open').setAttribute('aria-label','Ampliar '+s.alt)});tab.addEventListener('keydown',e=>{if(e.key==='ArrowRight'||e.key==='ArrowLeft'){e.preventDefault();const next=tabs[(index+(e.key==='ArrowRight'?1:-1)+tabs.length)%tabs.length];next.focus();next.click()}})});
const imageDialog=document.querySelector('#image-dialog'),purchaseDialog=document.querySelector('#purchase-dialog');
document.querySelector('#sample-open').addEventListener('click',()=>{document.querySelector('#dialog-image').src=sampleImage.src;document.querySelector('#dialog-image').alt=sampleImage.alt;imageDialog.showModal()});
document.querySelectorAll('.close-dialog').forEach(b=>b.addEventListener('click',()=>b.closest('dialog').close()));
document.querySelector('.close-purchase').addEventListener('click',()=>purchaseDialog.close());
document.querySelectorAll('dialog').forEach(d=>d.addEventListener('click',e=>{if(e.target===d){const r=d.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)d.close()}}));
document.querySelectorAll('[data-preview-buy]').forEach(b=>b.addEventListener('click',()=>{document.querySelector('#purchase-title').textContent='Edição '+b.dataset.previewBuy+' · '+(b.dataset.previewBuy==='Completa'?'R$29,90':'R$10');purchaseDialog.showModal()}));
document.querySelectorAll('.choice').forEach(b=>b.addEventListener('click',()=>{const summary=document.querySelector('.selected-summary');summary.hidden=false;summary.textContent='Você se interessou pela edição '+b.dataset.edition+'. Confira as respostas antes de continuar.'}));
if('IntersectionObserver' in window&&!matchMedia('(prefers-reduced-motion: reduce)').matches){document.documentElement.classList.add('motion-ready');const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');observer.unobserve(e.target)}}),{threshold:.08,rootMargin:'0px 0px -25px 0px'});document.querySelectorAll('.reveal').forEach((el)=>observer.observe(el));}
document.querySelectorAll('.next').forEach(a=>a.addEventListener('click',e=>{const target=document.querySelector(a.getAttribute('href'));if(target){e.preventDefault();target.scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth',block:'start'});history.replaceState(null,'',a.getAttribute('href'))}}));

const promiseRail=document.querySelector('.promise-strip');
if(promiseRail){promiseRail.outerHTML='<div class="discovery-marquee" aria-label="Destaques do kit"><div class="marquee-track"><span>✦ 52 LIÇÕES ORGANIZADAS</span><span>✦ ATIVIDADES PARA IMPRIMIR</span><span>✦ CRIANÇAS DE 4 A 8 ANOS</span><span>✦ GUIA PARA O PROFESSOR</span><span aria-hidden="true">✦ 52 LIÇÕES ORGANIZADAS</span><span aria-hidden="true">✦ ATIVIDADES PARA IMPRIMIR</span><span aria-hidden="true">✦ CRIANÇAS DE 4 A 8 ANOS</span><span aria-hidden="true">✦ GUIA PARA O PROFESSOR</span></div></div>'}
const helenaText=document.querySelector('.helena-signature span');if(helenaText)helenaText.textContent='Um olhar acolhedor para cada descoberta.';
const helenaImage=document.querySelector('.helena-photo img');if(helenaImage)helenaImage.alt='Tia Helena em uma sala infantil';
const helenaCaption=document.querySelector('.helena-photo figcaption');if(helenaCaption)helenaCaption.textContent='Conheça a Tia Helena';
const draftNote=document.querySelector('.draft-note');if(draftNote)draftNote.remove();
const profiles=[['assets/testimonial-ana.jpeg','Ana Martins'],['assets/testimonial-camila.jpeg','Camila Rocha'],['assets/testimonial-luciana.jpeg','Luciana Pereira']];
document.querySelectorAll('.quote-person').forEach((person,i)=>{const [src,name]=profiles[i];person.innerHTML='<img src="'+src+'" alt="'+name+'"><div><b>'+name+'</b></div>'});
const footer=document.querySelector('.footer-inner');if(footer&&!footer.querySelector('.footer-socials')){const socials=document.createElement('div');socials.className='footer-socials';socials.setAttribute('aria-label','Redes sociais');socials.innerHTML='<a href="https://www.instagram.com/domingodedescobertas/" target="_blank" rel="noreferrer" aria-label="Instagram">◎</a><a href="https://www.facebook.com/domingodedescobertas" target="_blank" rel="noreferrer" aria-label="Facebook">f</a><a href="https://www.youtube.com/@domingodedescobertas" target="_blank" rel="noreferrer" aria-label="YouTube">▶</a><a href="https://www.tiktok.com/@domingodedescobertas" target="_blank" rel="noreferrer" aria-label="TikTok">♪</a><a href="https://kiwify.com.br/@domingodedescobertas" target="_blank" rel="noreferrer" aria-label="Kiwify">K</a>';footer.querySelector('p').before(socials);footer.querySelector('small').textContent='@domingodedescobertas · © 2026 · Material digital em PDF.'}
const polish=document.createElement('style');polish.textContent=`
.discovery-marquee{margin-top:70px;overflow:hidden;border-block:1px solid #cbdccf;background:#f1f6ef;color:#37654C;white-space:nowrap}.marquee-track{display:flex;width:max-content;animation:marquee 24s linear infinite}.marquee-track span{display:inline-flex;align-items:center;min-height:58px;padding:0 28px;font-size:12px;letter-spacing:.09em;font-weight:800}.marquee-track span:nth-child(4n+2){color:#365F7D}.marquee-track span:nth-child(4n+3){color:#a2644f}@keyframes marquee{to{transform:translateX(-50%)}}.product-display{max-width:760px}.product-display>img{display:block;width:100%;height:auto;aspect-ratio:3/2;object-fit:contain;background:#e7f0f6}.quote-person>img{border-radius:50%;width:46px;height:46px;object-fit:cover;display:block;box-shadow:0 0 0 3px #eaf0e6}.footer-socials{display:flex;gap:10px;align-items:center}.footer-socials a{width:34px;height:34px;border-radius:50%;display:grid;place-items:center;text-decoration:none;background:#E5F1F8;color:#365F7D;font:800 17px Nunito;transition:transform .2s,background .2s}.footer-socials a:hover{background:#37654C;color:#fff;transform:translateY(-2px)}@media(max-width:760px){.discovery-marquee{margin-top:38px}.marquee-track{animation-duration:18s}.marquee-track span{min-height:50px;padding:0 18px;font-size:10px}.product-display>img{aspect-ratio:3/2;object-fit:contain}.footer-inner{flex-direction:column;align-items:flex-start;gap:20px}.footer-inner>p{text-align:left}}@media(prefers-reduced-motion:reduce){.marquee-track{animation:none}}
`;document.head.append(polish);
